import type { HermesSkillDefinition } from '@/lib/hermes/contracts/skill';

export const hermesSeedSkills: HermesSkillDefinition[] = [
  {
    name: 'Slides',
    category: 'Design',
    description: 'Membuat presentasi, pitch deck, dan deck visual terstruktur.',
    defaultAgent: 'Document Agent',
    plannerHints: ['buat outline', 'susun alur slide', 'hasilkan artifact presentasi'],
    requiredTools: ['llm.generate_text', 'document.compose_outline', 'filesystem.write_artifact'],
    validationRules: ['outline_minimum_sections', 'artifact_required'],
    outputFormats: ['PPTX', 'PDF', 'HTML'],
    supportedArtifactIds: ['pptx', 'pdf', 'html'],
    examplePrompts: ['Buat pitch deck startup AI kesehatan 10 slide'],
  },
  {
    name: 'Documents',
    category: 'Content',
    description: 'Menyusun proposal, SOP, laporan, dan dokumen hasil riset.',
    defaultAgent: 'Document Agent',
    plannerHints: ['analisis tujuan dokumen', 'susun struktur tulisan', 'hasilkan dokumen final'],
    requiredTools: ['llm.generate_text', 'document.compose_markdown', 'filesystem.write_artifact'],
    validationRules: ['content_required', 'artifact_required'],
    outputFormats: ['DOCX', 'PDF', 'Markdown'],
    supportedArtifactIds: ['docx', 'pdf', 'md'],
    examplePrompts: ['Buat proposal bisnis untuk klinik AI'],
  },
  {
    name: 'Images',
    category: 'Design',
    description: 'Membuat poster, ilustrasi, dan visual produk.',
    defaultAgent: 'Image Agent',
    plannerHints: ['analisis gaya visual', 'siapkan prompt gambar', 'hasilkan image artifact'],
    requiredTools: ['llm.generate_text', 'image.generate_asset', 'filesystem.write_artifact'],
    validationRules: ['artifact_required'],
    outputFormats: ['PNG', 'JPG'],
    supportedArtifactIds: ['png', 'jpg', 'svg'],
    examplePrompts: ['Buat poster grand opening kedai burger'],
  },
  {
    name: 'Sheets',
    category: 'Data',
    description: 'Analisis spreadsheet, cash flow, dan pembersihan data.',
    defaultAgent: 'Data & Sheets Agent',
    plannerHints: ['analisis struktur data', 'tentukan transformasi', 'hasilkan tabel atau file'],
    requiredTools: ['llm.generate_text', 'sheet.build_dataset', 'filesystem.write_artifact'],
    validationRules: ['table_rows_required', 'artifact_required'],
    outputFormats: ['XLSX', 'CSV', 'JSON Summary'],
    supportedArtifactIds: ['xlsx', 'csv'],
    examplePrompts: ['Buat estimasi cash flow startup SaaS'],
  },
  {
    name: 'Websites',
    category: 'Coding',
    description: 'Membangun source code website, landing page, dan komponen frontend.',
    defaultAgent: 'Project Builder Agent',
    plannerHints: ['pecah task menjadi section UI', 'susun component plan', 'hasilkan source artifact'],
    requiredTools: ['llm.generate_text', 'web.build_artifact', 'task.request_approval', 'filesystem.write_artifact'],
    validationRules: ['source_required', 'artifact_required'],
    outputFormats: ['HTML', 'Source Code (ZIP)', 'React/Tailwind Code'],
    supportedArtifactIds: ['html', 'zip'],
    examplePrompts: ['Buat landing page portofolio responsif'],
  },
  {
    name: 'Videos',
    category: 'Content',
    description: 'Membuat video konsep promosi pendek MP4 dengan visual gambar dan narasi suara AI.',
    defaultAgent: 'Video Agent',
    plannerHints: ['buat video', 'render video mp4', 'buat voiceover audio', 'hasilkan video mp4'],
    requiredTools: ['llm.generate_text', 'image.generate_asset', 'video.generate_mp4', 'filesystem.write_artifact'],
    validationRules: ['artifact_required'],
    outputFormats: ['MP4 Video', 'Video Concept Script'],
    supportedArtifactIds: ['mp4', 'md'],
    examplePrompts: ['Buat video promosi parfum mewah berdurasi singkat'],
  },
];
