import type { HermesToolDefinition } from '@/lib/hermes/contracts/tool';

export const hermesSeedTools: HermesToolDefinition[] = [
  {
    id: 'llm.generate_text',
    name: 'LLM Text Generation',
    category: 'llm',
    description: 'Menghasilkan teks terstruktur untuk rencana, dokumen, atau konten.',
    enabled: true,
    riskLevel: 'safe',
    requiresApproval: false,
  },
  {
    id: 'document.compose_markdown',
    name: 'Document Markdown Composer',
    category: 'document',
    description: 'Menyusun konten markdown final untuk dokumen atau laporan.',
    enabled: true,
    riskLevel: 'safe',
    requiresApproval: false,
  },
  {
    id: 'document.compose_outline',
    name: 'Document Outline Composer',
    category: 'document',
    description: 'Menyusun outline terstruktur untuk slide atau dokumen.',
    enabled: true,
    riskLevel: 'safe',
    requiresApproval: false,
  },
  {
    id: 'image.generate_asset',
    name: 'Image Asset Generator',
    category: 'image',
    description: 'Menghasilkan asset gambar nyata untuk task visual.',
    enabled: true,
    riskLevel: 'safe',
    requiresApproval: false,
  },
  {
    id: 'sheet.build_dataset',
    name: 'Sheet Dataset Builder',
    category: 'sheet',
    description: 'Membangun dataset tabular yang siap menjadi artifact.',
    enabled: true,
    riskLevel: 'safe',
    requiresApproval: false,
  },
  {
    id: 'web.build_artifact',
    name: 'Web Artifact Builder',
    category: 'web',
    description: 'Membangun artifact HTML atau paket web untuk task website.',
    enabled: true,
    riskLevel: 'guarded',
    requiresApproval: false,
  },
  {
    id: 'filesystem.write_artifact',
    name: 'Filesystem Artifact Writer',
    category: 'filesystem',
    description: 'Menulis metadata artifact ke runtime task.',
    enabled: true,
    riskLevel: 'guarded',
    requiresApproval: false,
  },
  {
    id: 'task.request_approval',
    name: 'Task Approval Request',
    category: 'workflow',
    description: 'Membuat permintaan approval untuk aksi berisiko.',
    enabled: true,
    riskLevel: 'dangerous',
    requiresApproval: true,
  },
  {
    id: 'video.generate_mp4',
    name: 'Video MP4 Renderer',
    category: 'video',
    description: 'Menggabungkan aset visual dan audio narasi menjadi berkas video MP4 menggunakan FFmpeg.',
    enabled: true,
    riskLevel: 'safe',
    requiresApproval: false,
  },
];
